config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  get 'dashboard/admin/index'
  get 'dashboard/admin/show'
  
  devise_for :users
  resources :subject do
    member do
      get 'enable_monitoring'
      get 'disable_monitoring'
    end
  end
  resources :lesson
  resources :user
  resources :attendance_sheet
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  has_many :attendance_sheets, dependent: :destroy

  validates :week, presence: true, uniqueness: { scope: :subject_id }
end

app/controllers/lesson_controller.rb
class LessonController < ApplicationController
  before_action :authenticate_admin!  
  before_action :validate_url!, only: [:create]
  
  def new
    @subject_id = url_params[:subject_id]
  end

  def create
    validate_url!
    
    subject_id = Subject.find(user_params[:subject_id]).id
    week_count = user_params[:week_count].to_i

    if insert_lessons(week_count, subject_id)
      redirect_to subject_index_path, notice: "#{week_count}回分の授業登録に成功しました"
    else
      redirect_to subject_index_path, alert: '登録に失敗しました'
    end
    # TODO: activerecord-importでバルクインサートに対応させる
  end

  def show
    # LEFT OUTER JOINでいい感じに書き直す
    @lesson = Lesson.find(params[:id])
    @attendance_sheets = @lesson.attendance_sheets
    @subject = @lesson.subject
    @users = @subject.users
    
    @situations = get_submission_situation(@users, @lesson)
  end

  def edit
    # pending
  end

  def update
    # pending
  end

  private

  def user_params
    params.permit(:week_count, :subject_id)
  end

  def url_params
    params.permit(:subject_id)
  end

  def insert_lessons(week_count, subject_id)
    # TODO: このメソッドはバルクインサートに対応したら削除する
    (1..week_count).each do |week|
      lesson = Lesson.new(week: week, subject_id: subject_id)
      lesson.save if lesson.valid?
    end

    return true
  end

  def authenticate_admin!
    unless current_user.admin?
      redirect_to dashboard_index_path, alert: 'このページへのアクセスは許可されていません'
    end
  end

  def validate_url!
    p redirect_to subject_index_path, alert: '登録に失敗しました' if user_params[:subject_id].empty?
  end

  def get_submission_situation(users, lesson)
    # ActiveRecordのLEFT OUTER JOINでたぶんどうにかできる
    situations = []

    @users = users.preload(:attendance_sheets)
    @lesson_id = lesson.id
    
    users.each do |user|
      situations << {
        st_num: user.st_num,
        name: user.name,
        submitted: user.attendance_sheets.where(lesson_id: @lesson_id).present?,
        attendance_sheet: user.attendance_sheets.where(lesson_id: @lesson_id).first
      }
    end

    situations
  end
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/views/lesson/edit.html.erb
<h1>Lesson#edit</h1>
<p>Find me in app/views/lesson/edit.html.erb</p>

app/views/lesson/new.html.erb
<h2>講義登録</h2>
<hr>
<div class="row">
  <div class="col-sm">
    <%= form_tag lesson_index_path, class: 'form-group' do %>
    <div class="form-group">
      <%= label_tag '授業回数' %>
      <%= text_field_tag :week_count, '15', class: 'form-control'%>
    </div>
    <div class="form-group">
      <%= hidden_field_tag :subject_id, @subject_id %>
    </div>
    <div class="form-group">
      <%= submit_tag '登録', class: 'btn btn-primary'%>
    </div>
    <% end %>
  </div>
</div>

app/views/lesson/show.html.erb
<h4><%= "#{@subject.term}年度" %></h4>
<h2><%= "#{@subject.display_name}" %></h2>
<h2><%= "第#{@lesson.week}回" %></h2>
<hr>
<h3>提出状況</h3>
<table class="table">
  <tr>
    <th>学籍番号</th>
    <th>名前</th>
    <th>提出状況</th>
    <th>提出日時</th>
  </tr>
  <% @situations.each do |s| %>
  <tr>
    <td><%= s[:st_num] %></td>
    <td><%= s[:name] %></td>
    <td>
      <% if s[:submitted] == true %>
      提出済み
      <% else %>
      未提出
      <% end %>
    </td>
    <td>
      <% if s[:submitted] %>
      <%= s[:attendance_sheet].created_at %>
      <% end %>
    </td>
  </tr>
  <% end%>
  </tr>
</table>