config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  get 'dashboard/admin/index'
  get 'dashboard/admin/show'
  
  devise_for :users
  resources :subject do
    member do
      get 'enable_monitoring'
      get 'disable_monitoring'
    end
  end
  resources :lesson
  resources :user
  resources :attendance_sheet
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance_sheet.rb
class AttendanceSheet < ApplicationRecord
  belongs_to :user
  belongs_to :lesson

  validates :comment, presence: true
  validates :summary, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :subject
  has_many :attendance_sheets, dependent: :destroy

  validates :week, presence: true, uniqueness: { scope: :subject_id }
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lessons, dependent: :destroy
  has_and_belongs_to_many :users

  validates :name, presence: true, uniqueness: true
  validates :display_name, presence: true
  validates :term, presence: true
end

app/models/subject_user.rb
class SubjectUser < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendance_sheets
  has_and_belongs_to_many :subjects

  devise :database_authenticatable, :trackable, :validatable
  enum role: {student: 0, auditor: 10, assistant: 20, teacher: 30}

  validates :st_num, presence: true, uniqueness: true
  validates :role,  inclusion: {in: User.roles.keys}

  def admin?
    return true if self.assistant? || self.teacher?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) {|u| u.permit(:st_num, :password)}
  end

  def after_sign_in_path_for(user)
    if user.admin?
      dashboard_admin_index_path
    else
      dashboard_index_path
    end
  end
end

app/controllers/attendance_sheet_controller.rb
class AttendanceSheetController < ApplicationController
  def index
  end

  def show
    @sheet = AttendanceSheet.preload(:lesson).find(params[:id])
    @lesson = @sheet.lesson
    @subject = @lesson.subject

    authenticate_sheet_user!(@sheet.user)
  end
  
  def new
    @sheet = AttendanceSheet.new
    @lesson = Lesson.find(url_params[:lesson_id])
    @subject = @lesson.subject
  end

  def create
    @sheet = AttendanceSheet.new(user_params)
    @sheet.user = current_user
    
    if @sheet.save
      redirect_to dashboard_index_path, notice: '提出に成功しました'
    else
      redirect_to dashboard_index_path, alert: '提出に失敗しました'
    end
  end

  def edit
    @sheet = AttendanceSheet.find(params[:id])
    @lesson = @sheet.lesson
    @subject = @lesson.subject

    authenticate_sheet_user!(@sheet.user)
  end

  def update
    @sheet = AttendanceSheet.find(params[:id])

    @sheet.summary = user_params[:summary]
    @sheet.comment = user_params[:comment]
    @sheet.question = user_params[:question]

    authenticate_sheet_user!(@sheet.user)
    
    if @sheet.save
      redirect_to dashboard_index_path, notice: '更新に成功しました'
    else
      redirect_to dashboard_index_path, alert:  '更新に失敗しました'
    end
  end

  private

  def user_params
    params.require(:attendance_sheet).permit(
      :summary,
      :comment,
      :question,
      :lesson_id
    )
  end

  def url_params
    params.permit(:lesson_id)
  end
  
  def authenticate_sheet_user!(user)
    unless current_user == user
      redirect_to dashboard_index_path, alert: '表示権限がありません'
    end
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @user = current_user
    @subjects = @user.subjects
  end
end

app/controllers/lesson_controller.rb
class LessonController < ApplicationController
  before_action :authenticate_admin!  
  before_action :validate_url!, only: [:create]
  
  def new
    @subject_id = url_params[:subject_id]
  end

  def create
    validate_url!
    
    subject_id = Subject.find(user_params[:subject_id]).id
    week_count = user_params[:week_count].to_i

    if insert_lessons(week_count, subject_id)
      redirect_to subject_index_path, notice: "#{week_count}回分の授業登録に成功しました"
    else
      redirect_to subject_index_path, alert: '登録に失敗しました'
    end
    # TODO: activerecord-importでバルクインサートに対応させる
  end

  def show
    # LEFT OUTER JOINでいい感じに書き直す
    @lesson = Lesson.find(params[:id])
    @attendance_sheets = @lesson.attendance_sheets
    @subject = @lesson.subject
    @users = @subject.users
    
    @situations = get_submission_situation(@users, @lesson)
  end

  def edit
    # pending
  end

  def update
    # pending
  end

  private

  def user_params
    params.permit(:week_count, :subject_id)
  end

  def url_params
    params.permit(:subject_id)
  end

  def insert_lessons(week_count, subject_id)
    # TODO: このメソッドはバルクインサートに対応したら削除する
    (1..week_count).each do |week|
      lesson = Lesson.new(week: week, subject_id: subject_id)
      lesson.save if lesson.valid?
    end

    return true
  end

  def authenticate_admin!
    unless current_user.admin?
      redirect_to dashboard_index_path, alert: 'このページへのアクセスは許可されていません'
    end
  end

  def validate_url!
    p redirect_to subject_index_path, alert: '登録に失敗しました' if user_params[:subject_id].empty?
  end

  def get_submission_situation(users, lesson)
    # ActiveRecordのLEFT OUTER JOINでたぶんどうにかできる
    situations = []

    @users = users.preload(:attendance_sheets)
    @lesson_id = lesson.id
    
    users.each do |user|
      situations << {
        st_num: user.st_num,
        name: user.name,
        submitted: user.attendance_sheets.where(lesson_id: @lesson_id).present?,
        attendance_sheet: user.attendance_sheets.where(lesson_id: @lesson_id).first
      }
    end

    situations
  end
end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @subjects = Subject.preload(:lessons).sort {|s1, s2| s1.term <=> s2.term}
  end

  def show
    @subject = Subject.find(params['id'])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(user_params)
    @week_count = week_count_params
    
    if @subject.save
      redirect_to subject_index_path, notice: '新規登録に成功しました'
    else
      render 'new', alert: '新規登録に失敗しました'
    end
  end
  
  def edit
    @subject = Subject.find(params['id'])
  end

  def update
    @subject = Subject.find(params['id'])

    @subject.name = user_params[:name]
    @subject.display_name = user_params[:display_name]
    @subject.term = user_params[:term]
    @subject.url = user_params[:url]
    
    if @subject.save
      redirect_to subject_index_path, notice: '更新に成功しました'
    else
      redirect_to subject_index_path, alert:  '更新に失敗しました'
    end
  end

  def enable_monitoring
    @subject = Subject.find(params['id'])
    @subject.monitored = true

    if @subject.save
      redirect_to subject_index_path, notice: '更新に成功しました'
    else
      redirect_to subject_index_path, alert:  '更新に失敗しました'
    end
  end

  def disable_monitoring
    @subject = Subject.find(params['id'])
    @subject.monitored = false

    if @subject.save
      redirect_to subject_index_path, notice: '更新に成功しました'
    else
      redirect_to subject_index_path, alert:  '更新に失敗しました'
    end
  end
  
  private

  def user_params
    params.require(:subject).permit(
      :name,
      :display_name,
      :term,
      :url,
    )
  end

  def week_count_params
    params.require(:subject).permit(
      :week_count
    )
  end
  
  def authenticate_admin!
    unless current_user.admin?
      redirect_to dashboard_index_path, alert: 'このページへのアクセスは許可されていません'
    end
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :authenticate_admin!
  
  def index
  end

  private 
  
  def authenticate_admin!
    unless current_user.admin?
      redirect_to dashboard_index_path, alert: 'このページへのアクセスは許可されていません'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendance_sheet_helper.rb
module AttendanceSheetHelper
end

app/helpers/dashboard/admin_helper.rb
module Dashboard::AdminHelper
end

app/helpers/dashboard/student_helper.rb
module Dashboard::StudentHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/lesson_helper.rb
module LessonHelper
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AttendanceSheetCollector</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap-theme.css">
  </head>
  <body>
    <div class="container-fruid">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
      <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'AttendanceSheet', dashboard_admin_index_path, class: 'navbar-brand' %>
      <% else %>
      <%= link_to 'AttendanceSheet', dashboard_index_path, class: 'navbar-brand' %>
      <% end %>
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="Navbar">
        <% if user_signed_in? && current_user.admin? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to '実施監視', dashboard_admin_index_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '授業管理', subject_index_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'ユーザ管理', user_index_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to '学生ページ', dashboard_index_path, class: 'nav-link' %>
          </li>
        </ul>
        <% end %>
        <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        </ul>
        <% end %>
      </div>
    </nav>
    </div>
    <div class="container">
      <% if notice.present? %>
        <p class="alert alert-info"><%= notice %></p>
      <% end %>
      <% if alert.present? %>
        <p class="alert alert-warning"><%= alert %></p>
      <% end %>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>